RaceDescription = {}
RaceDescription.name = "n/a"
RaceDescription.baseArmorClass = 0

HumanRaceDescription = new RaceDescription
HumanRaceDescription.name = "human"
HumanRaceDescription.baseArmorClass = 10

KoboldRaceDescription = new RaceDescription
KoboldRaceDescription.name = "kobold"
KoboldRaceDescription.baseArmorClass = 10

RaceDescriptions = {
	"human": new HumanRaceDescription,
	"kobold": new KoboldRaceDescription }
