PLAYER_INITIAL_WEAPON = weapons.dagger // weapons.shortSword
PLAYER_INITIAL_SHIELD = null //shields.buckler
PLAYER_INITIAL_ARMOR = null

PLAYER_INITIAL_INVENTORY = [
	items.basicHealingPotion,
	//items.basicHealingPotion,
	//items.basicHealingPotion,
	//items.basicHealingPotion,
	//items.basicHealingPotion,
	//items.greaterHealingPotion,
	//items.greaterHealingPotion,
	//items.greaterHealingPotion,
	//items.superiorHealingPotion,
]
